################## GLOBAL SETTINGS ##################
#Future proofing! Don't change this. I can't stop you, but doing so can corrupt your config and that makes it sad.
configVersion: 1.04
debug: false

#How many menus do you want? Default is 1. 
menus: 1

#Menus have been moved to their own files for easier editing of multiple menus.

