name: PotatoJSONMenu
version: 1.04
main: a0b75f1b744114830919a5684e1eba611.PluginMain
author: LadyPotaty
description: Utilizes Vanilla's JSON component to make highly customizable chat menus.
api-version: 1.13
commands:
  jsonmenu:
    description: Admin options for JSON Menus
    permission: potato.jsonmenu.admin
  menu:
    description: Base command for menus, no arguments defaults to first menu.
    permission: potato.jsonmenu
