name: PotatoJSONMenu
version: 1.02
main: a29ba4648d8f14c52b3cb1fa21a17c279.PluginMain
author: LadyPotaty
description: Utilizes Vanilla's JSON component to make highly customizable chat menus.
api-version: 1.13
commands:
  jsonmenu:
    description: Admin options for JSON Menus
    permission: potato.jsonmenu.admin
  menu:
    description: Base command for menus, no arguments defaults to first menu.
    permission: potato.jsonmenu
